language: node_js
node_js: 8.9.4

cache:
  yarn: true
  directories:
   - node_modules

install:
 - yarn --silent

script:
 - yarn run mdlint

deploy:
  provider: script
  script: node deploy.js
  skip_cleanup: true
  on:
    branch: master
